### ISSUE TITLE
Using the KernelGAN to obtain Blur Kernel of Monocolor Images or Image with more than 3 channels (Hyperspectral Images)

### ISSUE THREAD

**Issue by ferrerorocher-gpu** [sefibk/KernelGAN#13]
Dear Team,
I was reading through the codes of KernelGAN and I am interested in adopting the code for :
1. Monocolor (1 Channel) Image.
2. Hyperspectral Images (More than 3 color channels).
Could put let me know the alterations the code requires for this above purpose?

In addition, I need to output the (Estimated) Blurred Image after the training of the GAN Network. For this we need to pass the Entire Input LR image (Not patch-by-patch as done during training) to the Generator network (after the training has been done) and get the Output (Blurred LR Image) of the Generator. Please suggest ways to do this.

**Comment by sefibk** [comment]
1. Note that the generator downscales a single channel at a time by treating the image as a batch of 3. I think all you should do is unsqueeze( ) your image at axis 1 and it should work plug&play.
If not, you should skip the 'swap_axis( )' function that is called in networks.py (lines 27, 31). 
If this doesn't work, you can simply concat you single channel 3 times, although this is redundant.
2. In continuation to the above. 'swap_axis( )' should transform the 4 channel image to a batch of 4 single channel images and support your image.

Since the generator is fully Convolutional it is agnostic to the input size. You can simply forward pass your entire image through G and it will downscale it with the estimated kernel.
Alternatively, once you get the estimated kernel

**Comment by ferrerorocher-gpu** [comment]
For Images having more than 3 channels, there will be the following hurdles.
1.  In util.py, create_gradient_map() has a function rgb2gray(). Please let me know how this can be adapted for multispectral images. Should we create individual maps for each channel and estimate the kernels of each channel independently? However, this leads to issue of different blur kernels for different image channels.
2. In Class Discriminator,  self.first_layer has 3 input channels. I assume that for an "x" channel image, the no. of input channels will be = x.
Please let me know your thoughts.

**Comment by sefibk** [comment]
First, let me point out - KernelGAN was created with natural image priors in thought, I am not familiar with Hyperspectral so I am not confident it should work. However - for B&W we have results in our website that were created just by concatenating the single channel X3.
For technical solutions I can suggest:
1. rgb2gray is used to generate a gradient map in order to feed the network crops with high gradient content. You can override the 'create_gradient_map' function according to your type of data to provide a map of the gradients in your image. Or o.w. in data.py skip line 49 and don't provide 'p' in 50, 51 - NOTE: this will loose the functionality of the crop choices.
2. You are correct - I forgot. You can simply adjust the in_channels from 3 to 4. Again - I don't have experience with this type of data so no guarantees.

**Comment by mlxht990720** [comment]
Excuse me! Have you solved this problem yet? I still can't get satisfying results on my Hyperspectral Images Datasets

**Comment by sefibk** [comment]
The model was not developed for Hyperspectral images so it is not something I am trying to solve for
