### ISSUE TITLE
real LR

### ISSUE THREAD

**Issue by zhuangzhong** [sefibk/KernelGAN#24]
How do I generate div2k train 800 real LR image with your method? I saw that cubic is used in your imresize function, not kernelGAN

**Comment by sefibk** [comment]
To be "on the safe side" - simply use the Matlab Imresize function with whatever kernel you want.
My Imresize is a "Python translation" of the Matlab's one. If you provide it with a kernel (rather than None) you will get the LR image. 
`def imresize(im, scale_factor=None, output_shape=None, **kernel=None**, antialiasing=True, kernel_shift_flag=False):
`
