### ISSUE TITLE
About GAN loss and generator function

### ISSUE THREAD

**Issue by r1ckya** [sefibk/KernelGAN#5]
Hi, thanks for the great work.

I have a couple questions about GAN setup.

1) As I understand, the paper says that generator purpose is to model downsampling operation which is applying kernel to an image followed by subsampling operation like here https://github.com/sefibk/KernelGAN/blob/master/util.py#L37
https://github.com/sefibk/KernelGAN/blob/master/imresize.py#L157
but when I look on the generator structure I see it done in a different order https://github.com/sefibk/KernelGAN/blob/master/networks.py#L11
(subsampling + applying kernel). So any kernel from the generator would be dilated 25x25 kernel instead of 13x13 kernel as the paper says. Is this intentional?

2) LSGAN loss function L1 instead of L2 (nn.MSELoss)
https://github.com/sefibk/KernelGAN/blob/master/loss.py#L15

**Comment by r1ckya** [comment]
For some reason I thought that first conv is 1x1 but its actually 7x7. Anyway receptive field is not 13x13
![image](https://user-images.githubusercontent.com/36926096/68933206-3f3a3900-07a5-11ea-91c0-51f9d26ae67a.png)

**Comment by sefibk** [comment]
Hi,
1. It is an interesting point! **I have to think about it further....**, but at first thought - consider the following points:
- How do the deep channels (64 if I recall) in the hidden layer effect your observation? Will the dilated occur anyway?
- The network can learn to produce an undiluted kernel since a downscaling with such kernel will probably not fool the discriminator - but this was not intentional. 

You can easily check what you are claiming by simply running the network > extract the kernel (using a ready function in the utils) > compare the downscaled image using the network with the imresize function that accepts the extracted kernel.

2. You are correct, **thank you!!!** - I will correct the paper accordingly.

**Comment by sefibk** [comment]
Regarding 1 - You are correct - I will fix this issue and update the project although I will be getting to it only in a while.
Thank you again for the enlightenment....

**Comment by sefibk** [comment]
Thanks a lot for the great comments.
The paper + code were updated
