### ISSUE TITLE
Result with misalignment and artifact

### ISSUE THREAD

**Issue by lylllove** [sefibk/KernelGAN#6]
Thank you for your great work!
I'm trying some super resolution research work for remote sensing images。In my field,there are always no high resolution  images for supervised learning , so I would like to take some unsupervised approach for my research.
When I do some test with your code in my dataset ,I found  that most of the result images had anomalies. Some of them were mialignment , others were full of artifact,or noise.
I've tried to increase the iters to 6000, while it didn't  make difference.
I will paste two typical results in this ISSUE。
I wonder if you have noticed this phenomena ?
Or some suggestion for me ?
Misalignment example:
![image](https://user-images.githubusercontent.com/45196123/69020088-5cae1380-09ee-11ea-85c6-b9db890c3e5f.png)
Noise example:
![image](https://user-images.githubusercontent.com/45196123/69020218-b9a9c980-09ee-11ea-966a-f34973914c24.png)
![image](https://user-images.githubusercontent.com/45196123/69020628-1e195880-09f0-11ea-80b5-9f603b3ef402.png)
![image](https://user-images.githubusercontent.com/45196123/69020827-d3e4a700-09f0-11ea-9d41-cbabbb5da515.png)

**Comment by sefibk** [comment]
Note that the SR process is done by a different work (ZSSR) that I plugged into the Github project for simplicity of use. 
When combining 2 methods (kernel est. + SR) it is hard to point out which one is creating the artefacts, therefore, you should try to use another SR method (that accepts the kernel) to try to see who is the problem.
But from my experience here are some insights:
1. noise usually happens because ZSSR either adds to much noise or too little - it is a hyper-parameter inserted to the network. **Try tuning it and see the effects**.
2. Misalignments occur in cases that the estimated kernel is not centralised. It should not happen in KernelGAN since we have a constraint for it to be centred. In addition, it is hard to see misalignment in side-by-side images, you must view them on top of each other and flicker. 
3. What I see in these images could be "ringing" where edges are over-enhanced. This can occur if the estimated kernel is too "wide" (causing a severe blur) and the SR method will learn to over-sharpen the image, i.e. ringing.
4. Increasing the iterations won't help. In fact, it always converges before the 3K iterations.

**Comment by lylllove** [comment]
Thank you for your suggestion and I will try some.

**Comment by vladpaunescu** [comment]
Same problem here, every picture has some artifact present. No super-resolution possible.

**Comment by lylllove** [comment]
When I added some noise in ZSSR, the performance enhanced!

**Comment by sefibk** [comment]
> When I added some noise in ZSSR, the performance enhanced!

Thanks for the update. 
This Git repo is the official implementation for KernelGAN, hence the kernel estimation should be correct. I provided ZSSR for convenience but you should note that it is NOT the official page, and it might be not up to date.
